"""Seed data: Artists, origin metadata and genre links."""
from __future__ import annotations


# artist -> [(genre, weight)]
ARTISTS: dict[str, list[tuple[str, float]]] = {
    "Future": [("Trap", 10), ("Hip Hop", 8), ("R&B", 4)],
    "Metro Boomin": [("Trap", 9), ("Hip Hop", 8)],
    "Travis Scott": [("Trap", 8), ("Hip Hop", 9), ("R&B", 5)],
    "21 Savage": [("Trap", 8), ("Drill", 6), ("Hip Hop", 7)],
    "Don Toliver": [("Trap", 6), ("R&B", 7)],
    "Drake": [("Hip Hop", 9), ("Trap", 6), ("R&B", 8)],
    "Kendrick Lamar": [("Hip Hop", 10), ("West Coast", 9)],
    "J. Cole": [("Hip Hop", 9), ("Soul", 5)],
    "Nas": [("Hip Hop", 9), ("East Coast", 10), ("Boom Bap", 8)],
    "DJ Premier": [("Boom Bap", 10), ("East Coast", 9)],
    "J Dilla": [("Boom Bap", 10), ("Lo-Fi", 8), ("Soul", 7)],
    "Nujabes": [("Lo-Fi", 10), ("Boom Bap", 6)],
    "Pop Smoke": [("Drill", 10), ("Trap", 6)],
    "Chief Keef": [("Drill", 9), ("Trap", 7)],
    "Central Cee": [("Drill", 8)],
    "SZA": [("R&B", 10), ("Soul", 7)],
    "Brent Faiyaz": [("R&B", 10), ("Soul", 8), ("Hip Hop", 5)],
    "The Weeknd": [("R&B", 9), ("Pop", 8)],
    "Summer Walker": [("R&B", 8)],
    "D'Angelo": [("Soul", 10), ("R&B", 8)],
    "Erykah Badu": [("Soul", 10), ("R&B", 7)],
    "Tom Misch": [("Lo-Fi", 7), ("Soul", 6)],
    "Alchemist": [("Boom Bap", 9), ("Experimental", 7)],
    "Bad Bunny": [("Reggaeton", 10), ("Latin Trap", 9), ("Pop", 6)],
    "Anuel AA": [("Latin Trap", 10), ("Reggaeton", 8)],
    "Ozuna": [("Reggaeton", 9), ("Latin Trap", 7)],
    "Feid": [("Reggaeton", 9)],
    "Myke Towers": [("Latin Trap", 9), ("Reggaeton", 7)],
    "El Alfa": [("Reggaeton", 8), ("Dancehall", 5)],
    "Coi Leray": [("Jersey Club", 8), ("Hip Hop", 6)],
    "Lil Uzi Vert": [("Jersey Club", 7), ("Trap", 7)],
    "Fisher": [("Tech House", 9), ("House", 7)],
    "Disclosure": [("House", 9), ("Deep House", 8)],
    "Kaytranada": [("House", 8), ("R&B", 6)],
    "Fred Again": [("House", 9), ("Experimental", 6)],
    "Burna Boy": [("Afrobeat", 10), ("Dancehall", 6)],
    "Wizkid": [("Afrobeat", 10), ("R&B", 6)],
    "Tems": [("Afrobeat", 9), ("R&B", 8)],
    "Vybz Kartel": [("Dancehall", 10)],
    "Skillibeng": [("Dancehall", 9), ("Hip Hop", 5)],
    "Dua Lipa": [("Pop", 9), ("House", 6)],
    "Billie Eilish": [("Pop", 9), ("Experimental", 6)],
    "Ghostemane": [("Phonk", 9), ("Experimental", 7)],
    "Kordhell": [("Phonk", 9)],
    "DJ Yung Vamp": [("Phonk", 8)],
    "Snoop Dogg": [("West Coast", 10), ("Hip Hop", 7)],
    "YG": [("West Coast", 9)],
    "Wu-Tang Clan": [("East Coast", 10), ("Boom Bap", 9)],
    "Griselda": [("East Coast", 9), ("Boom Bap", 9)],
    "Arca": [("Experimental", 10)],
    "Flying Lotus": [("Experimental", 9), ("Lo-Fi", 6)],
    "Rosalía": [("Reggaeton", 7), ("Experimental", 8), ("Pop", 7)],
    "Rauw Alejandro": [("Reggaeton", 9), ("Pop", 6)],
    # --- Wave 2 (2024-2026 research: rage/underground, Detroit/Flint,
    # --- sexy drill, UK drill, R&B risers, Afrobeats, amapiano, club) ---
    "Yeat": [("Trap", 9), ("Hip Hop", 6), ("Experimental", 6)],
    "Ken Carson": [("Trap", 9), ("Experimental", 6)],
    "Destroy Lonely": [("Trap", 8), ("Experimental", 6)],
    "Playboi Carti": [("Trap", 9), ("Hip Hop", 8), ("Experimental", 7)],
    "Homixide Gang": [("Trap", 7)],
    "2hollis": [("Experimental", 9), ("Trap", 6), ("Pop", 5)],
    "Nettspend": [("Trap", 7), ("Experimental", 7)],
    "EsDeeKid": [("Trap", 7), ("Drill", 6), ("Experimental", 5)],
    "fakemink": [("Experimental", 8), ("Hip Hop", 5)],
    "Zukenee": [("Trap", 7), ("Hip Hop", 6)],
    "Apollored1": [("Trap", 7), ("Experimental", 6)],
    "Babyface Ray": [("Trap", 8), ("Hip Hop", 7)],
    "Veeze": [("Trap", 8), ("Hip Hop", 6)],
    "Skilla Baby": [("Trap", 7), ("Hip Hop", 7)],
    "Rio Da Yung OG": [("Trap", 7), ("Hip Hop", 6)],
    "Babyfxce E": [("Trap", 6)],
    "Lelo": [("Trap", 6), ("Hip Hop", 7), ("Experimental", 5)],
    "Boldy James": [("Boom Bap", 9), ("Hip Hop", 7)],
    "Fivio Foreign": [("Drill", 9), ("Trap", 6)],
    "Sheff G": [("Drill", 8)],
    "Sleepy Hallow": [("Drill", 8), ("R&B", 5)],
    "22Gz": [("Drill", 7)],
    "Cash Cobain": [("Drill", 9), ("Jersey Club", 7), ("R&B", 5)],
    "Chow Lee": [("Drill", 7), ("Jersey Club", 6)],
    "Shawny Binladen": [("Drill", 7)],
    "Headie One": [("Drill", 9), ("Hip Hop", 6)],
    "Nemzzz": [("Drill", 8), ("Jersey Club", 5)],
    "Russ Millions": [("Drill", 7)],
    "K-Trap": [("Drill", 7)],
    "Tyler the Creator": [("Hip Hop", 9), ("West Coast", 7), ("Experimental", 8)],
    "Doechii": [("Hip Hop", 9), ("Pop", 7), ("R&B", 6)],
    "JID": [("Hip Hop", 9), ("Soul", 5)],
    "Vince Staples": [("Hip Hop", 8), ("West Coast", 9)],
    "Denzel Curry": [("Hip Hop", 8), ("Trap", 6), ("Experimental", 5)],
    "Baby Keem": [("Hip Hop", 8), ("West Coast", 6)],
    "Smino": [("Hip Hop", 8), ("Soul", 6), ("R&B", 6)],
    "Saba": [("Hip Hop", 8), ("Soul", 5)],
    "Ray Vaughn": [("Hip Hop", 7), ("West Coast", 7)],
    "Joey Bada$$": [("Hip Hop", 8), ("East Coast", 9), ("Boom Bap", 7)],
    "Benny the Butcher": [("Boom Bap", 9), ("East Coast", 9), ("Hip Hop", 7)],
    "Conway the Machine": [("Boom Bap", 9), ("East Coast", 8)],
    "Rome Streetz": [("Boom Bap", 9), ("East Coast", 8)],
    "Roc Marciano": [("Boom Bap", 10), ("East Coast", 8)],
    "Larry June": [("West Coast", 9), ("Hip Hop", 7), ("Soul", 5)],
    "Curren$y": [("West Coast", 8), ("Hip Hop", 7)],
    "03 Greedo": [("West Coast", 8), ("Trap", 6)],
    "4batz": [("R&B", 9), ("Hip Hop", 6)],
    "Tommy Richman": [("R&B", 8), ("Pop", 7)],
    "Leon Thomas": [("R&B", 10), ("Soul", 7)],
    "Coco Jones": [("R&B", 9)],
    "Muni Long": [("R&B", 9)],
    "Fridayy": [("R&B", 9), ("Hip Hop", 5)],
    "PARTYNEXTDOOR": [("R&B", 9), ("Hip Hop", 5)],
    "Daniel Caesar": [("R&B", 9), ("Soul", 7)],
    "H.E.R.": [("R&B", 9), ("Soul", 6)],
    "Kehlani": [("R&B", 8), ("Pop", 5)],
    "Destin Conrad": [("R&B", 8)],
    "Lucky Daye": [("R&B", 8), ("Soul", 6)],
    "Silk Sonic": [("Soul", 9), ("R&B", 9)],
    "Leon Bridges": [("Soul", 9), ("R&B", 6)],
    "Black Pumas": [("Soul", 8), ("Experimental", 5)],
    "Sabrina Carpenter": [("Pop", 9)],
    "Chappell Roan": [("Pop", 9), ("Experimental", 5)],
    "Charli XCX": [("Pop", 9), ("Experimental", 8), ("House", 5)],
    "Olivia Rodrigo": [("Pop", 8)],
    "Tate McRae": [("Pop", 8), ("R&B", 5)],
    "Doja Cat": [("Pop", 8), ("Hip Hop", 7), ("R&B", 6)],
    "Asake": [("Afrobeat", 10), ("Dancehall", 5)],
    "Ayra Starr": [("Afrobeat", 9), ("R&B", 7), ("Pop", 6)],
    "Rema": [("Afrobeat", 9), ("Pop", 7), ("Trap", 5)],
    "Tyla": [("Afrobeat", 9), ("R&B", 8), ("Pop", 8), ("Dancehall", 5)],
    "Davido": [("Afrobeat", 9)],
    "Fireboy DML": [("Afrobeat", 8), ("R&B", 6)],
    "Omah Lay": [("Afrobeat", 8), ("R&B", 6)],
    "Seyi Vibez": [("Afrobeat", 8)],
    "Shallipopi": [("Afrobeat", 7), ("Hip Hop", 5)],
    "Uncle Waffles": [("Afrobeat", 7), ("House", 8)],
    "Young Miko": [("Latin Trap", 9), ("Reggaeton", 8), ("Pop", 5)],
    "Quevedo": [("Reggaeton", 9), ("Pop", 6)],
    "Mora": [("Reggaeton", 8), ("Latin Trap", 8)],
    "Jhayco": [("Reggaeton", 9), ("Latin Trap", 7)],
    "2Rare": [("Jersey Club", 9), ("Hip Hop", 6)],
    "Bandmanrill": [("Jersey Club", 9), ("Drill", 7)],
    "MCVERTT": [("Jersey Club", 8)],
    "John Summit": [("House", 9), ("Tech House", 7)],
    "Dom Dolla": [("House", 9), ("Tech House", 7)],
    "Mau P": [("Tech House", 9), ("House", 7)],
    "Black Coffee": [("Deep House", 10), ("House", 7), ("Afrobeat", 6)],
    "Keinemusik": [("Deep House", 9), ("House", 7), ("Afrobeat", 6)],
    "Masicka": [("Dancehall", 9), ("Hip Hop", 5)],
    "Chronic Law": [("Dancehall", 8)],
    "Shenseea": [("Dancehall", 8), ("Pop", 6), ("R&B", 5)],
    "Alkaline": [("Dancehall", 8)],
    "Spice": [("Dancehall", 7)],
    "idealism": [("Lo-Fi", 9)],
    "dryhope": [("Lo-Fi", 8)],
    "sleepy fish": [("Lo-Fi", 8)],
    "Pharmacist": [("Phonk", 9)],
    "DVRST": [("Phonk", 8)],
    "Ghostface Playa": [("Phonk", 9), ("Experimental", 5)],
    "Kaito Shoma": [("Phonk", 8)],
    "Quadeca": [("Experimental", 9), ("Hip Hop", 6), ("Pop", 5)],
    "Jane Remover": [("Experimental", 9)],
    "JPEGMAFIA": [("Experimental", 9), ("Hip Hop", 7), ("Boom Bap", 5)],
    # --- Wave 3 (LATAM + Spanish-speaking) ---
    "Duki": [("Trap", 9), ("Hip Hop", 7)],
    "YSY A": [("Trap", 8), ("Hip Hop", 6)],
    "Bizarrap": [("Trap", 7), ("Latin Trap", 7), ("Pop", 6)],
    "Nicki Nicole": [("Latin Trap", 8), ("R&B", 7), ("Pop", 6)],
    "Cazzu": [("Latin Trap", 8), ("Reggaeton", 6)],
    "Khea": [("Latin Trap", 7), ("Reggaeton", 6)],
    "Nathy Peluso": [("R&B", 8), ("Hip Hop", 7), ("Latin Trap", 6)],
    "Cruz Cafuné": [("Hip Hop", 8), ("Trap", 7)],
    "Delaossa": [("Hip Hop", 7), ("Trap", 6)],
    "Rels B": [("R&B", 8), ("Latin Trap", 7), ("Reggaeton", 7)],
    "Morad": [("Drill", 8), ("Trap", 6)],
    "Beny Jr": [("Drill", 7), ("Trap", 5)],
    "JC Reyes": [("Reggaeton", 7), ("Latin Trap", 7)],
    "Cris Mj": [("Reggaeton", 9), ("Latin Trap", 7)],
    "FloyyMenor": [("Reggaeton", 8), ("Latin Trap", 6)],
    "Blessd": [("Reggaeton", 9), ("Latin Trap", 7)],
    "Ryan Castro": [("Reggaeton", 9), ("Latin Trap", 6)],
    "Karol G": [("Reggaeton", 9), ("Latin Trap", 7), ("Pop", 7)],
    "Shakira": [("Pop", 8), ("Reggaeton", 6), ("Dancehall", 5)],
    "J Balvin": [("Reggaeton", 9), ("Pop", 7), ("Dancehall", 6)],
    "Santa Fe Klan": [("Hip Hop", 9), ("Trap", 6)],
    "Alemán": [("Hip Hop", 8), ("Trap", 7)],
    "Gera MX": [("Hip Hop", 7), ("Trap", 6)],
    "Snow Tha Product": [("Hip Hop", 7), ("Latin Trap", 6)],
    "Eladio Carrión": [("Trap", 9), ("Latin Trap", 9), ("Drill", 6)],
    "Yovngchimi": [("Drill", 8), ("Trap", 7), ("Latin Trap", 6)],
    "Hades66": [("Drill", 7), ("Trap", 6)],
    # --- Wave 4 (hip hop en español: boom bap ES/Latam, R&B alt, pop ES) ---
    "Nach": [("Hip Hop", 9), ("Boom Bap", 10)],
    "SFDK": [("Hip Hop", 9), ("Boom Bap", 9)],
    "Violadores del Verso": [("Hip Hop", 9), ("Boom Bap", 10)],
    "ToteKing": [("Hip Hop", 8), ("Boom Bap", 8)],
    "Shotta": [("Hip Hop", 7), ("Boom Bap", 7)],
    "Rapsusklei": [("Hip Hop", 8), ("Boom Bap", 8)],
    "El Chojin": [("Hip Hop", 8), ("Boom Bap", 7)],
    "Ayax y Prok": [("Hip Hop", 8), ("Boom Bap", 8)],
    "Natos y Waor": [("Hip Hop", 7), ("Trap", 6)],
    "Foyone": [("Hip Hop", 7), ("Boom Bap", 8)],
    "Canserbero": [("Hip Hop", 10), ("Boom Bap", 10)],
    "Apache": [("Hip Hop", 8), ("Boom Bap", 8)],
    "Lil Supa": [("Hip Hop", 8), ("Boom Bap", 8)],
    "Akapellah": [("Hip Hop", 8), ("Trap", 6)],
    "Acru": [("Hip Hop", 8), ("Boom Bap", 7)],
    "Trueno": [("Hip Hop", 9), ("Trap", 8)],
    "Wos": [("Hip Hop", 9), ("Trap", 6), ("Experimental", 6)],
    "Ca7riel y Paco Amoroso": [("Hip Hop", 7), ("Experimental", 9), ("Pop", 6)],
    "Dillom": [("Trap", 8), ("Experimental", 8), ("Hip Hop", 6)],
    "Ana Tijoux": [("Hip Hop", 8), ("Soul", 6), ("Experimental", 5)],
    "Portavoz": [("Hip Hop", 7), ("Boom Bap", 8)],
    "Cartel de Santa": [("Hip Hop", 9), ("Trap", 6)],
    "C-Kan": [("Hip Hop", 8), ("Trap", 6)],
    "Lápiz Conciente": [("Hip Hop", 9), ("Boom Bap", 9)],
    "Vico C": [("Hip Hop", 9), ("Boom Bap", 8)],
    "Tego Calderón": [("Hip Hop", 9), ("Reggaeton", 7), ("Dancehall", 6)],
    "Orishas": [("Hip Hop", 8), ("Soul", 6), ("Dancehall", 5)],
    "Los Aldeanos": [("Hip Hop", 8), ("Boom Bap", 9)],
    "Villano Antillano": [("Trap", 8), ("Latin Trap", 8), ("Hip Hop", 6)],
    "Neutro Shorty": [("Trap", 8), ("Latin Trap", 7)],
    "Big Soto": [("Trap", 7), ("Latin Trap", 7)],
    "Pablo Chill-E": [("Trap", 7), ("Latin Trap", 6)],
    "Brray": [("Trap", 7), ("Latin Trap", 8)],
    "Lomiiel": [("Reggaeton", 8), ("Dancehall", 7)],
    "Little Homie": [("Drill", 7), ("Trap", 6)],
    "El Bobe": [("Drill", 7), ("Trap", 6)],
    "Sech": [("Reggaeton", 8), ("R&B", 8), ("Dancehall", 7)],
    "Dalex": [("R&B", 8), ("Latin Trap", 8), ("Reggaeton", 7)],
    "Lenny Tavárez": [("Latin Trap", 8), ("Reggaeton", 7)],
    "Lyanno": [("Latin Trap", 7), ("R&B", 7), ("Reggaeton", 6)],
    "Piso 21": [("Pop", 7), ("Reggaeton", 8)],
    "Kafu Banton": [("Dancehall", 9), ("Reggaeton", 6)],
    "Girl Ultra": [("R&B", 8), ("Lo-Fi", 7)],
    "Nsqk": [("R&B", 7), ("Lo-Fi", 8), ("Experimental", 6)],
    "Cuco": [("Lo-Fi", 8), ("R&B", 7), ("Soul", 5)],
    "Omar Apollo": [("R&B", 9), ("Soul", 7), ("Pop", 6)],
    "Kali Uchis": [("R&B", 9), ("Pop", 8), ("Soul", 6)],
    "Micro TDH": [("R&B", 7), ("Latin Trap", 7), ("Pop", 6)],
    "Aitana": [("Pop", 8)],
    "Lola Índigo": [("Pop", 8), ("Reggaeton", 5)],
    "Manuel Turizo": [("Reggaeton", 8), ("Pop", 8)],
    "Sebastián Yatra": [("Pop", 8), ("Reggaeton", 7)],
    "Camilo": [("Pop", 8)],
    "Emilia": [("Pop", 8), ("Reggaeton", 6)],
    "Tini": [("Pop", 8)],
    "María Becerra": [("Pop", 7), ("Reggaeton", 7), ("Latin Trap", 6)],
    "Cimafunk": [("Soul", 8), ("R&B", 6), ("Dancehall", 5)],
    "Chancha Vía Circuito": [("Experimental", 8)],
    "Nicola Cruz": [("Experimental", 8)],
    "C. Tangana": [("Hip Hop", 8), ("Pop", 8), ("Experimental", 7)],
    # --- Wave 5 (global fame: US/UK legends + currents, EDM, soul greats,
    # --- reggaeton OGs, Spain rap, phonk/lo-fi pioneers) ---
    "A$AP Rocky": [("Hip Hop", 9), ("Trap", 7), ("Experimental", 6)],
    "Nicki Minaj": [("Hip Hop", 9), ("Trap", 8), ("Pop", 7)],
    "Cardi B": [("Hip Hop", 8), ("Trap", 8)],
    "Megan Thee Stallion": [("Hip Hop", 8), ("Trap", 7)],
    "GloRilla": [("Trap", 8), ("Hip Hop", 7)],
    "Sexyy Red": [("Trap", 8), ("Hip Hop", 6)],
    "Latto": [("Hip Hop", 8), ("Trap", 7)],
    "Ice Spice": [("Drill", 8), ("Trap", 7), ("Pop", 6)],
    "Lil Baby": [("Trap", 9), ("Hip Hop", 8)],
    "Gunna": [("Trap", 9), ("Hip Hop", 7)],
    "Young Thug": [("Trap", 9), ("Hip Hop", 8), ("Experimental", 6)],
    "Juice WRLD": [("Hip Hop", 9), ("Trap", 8), ("Experimental", 6), ("Pop", 6)],
    "XXXTentacion": [("Hip Hop", 8), ("Trap", 7), ("Experimental", 7)],
    "Lil Peep": [("Hip Hop", 7), ("Experimental", 8), ("Trap", 6)],
    "Post Malone": [("Hip Hop", 8), ("Pop", 9), ("Trap", 6)],
    "Eminem": [("Hip Hop", 10), ("Boom Bap", 8)],
    "50 Cent": [("Hip Hop", 9), ("East Coast", 8)],
    "Lil Wayne": [("Hip Hop", 9), ("Trap", 7)],
    "Rick Ross": [("Hip Hop", 8), ("Trap", 8)],
    "Meek Mill": [("Hip Hop", 8), ("Trap", 7), ("East Coast", 7)],
    "Big Sean": [("Hip Hop", 8)],
    "Wiz Khalifa": [("Hip Hop", 8), ("Trap", 7), ("West Coast", 7)],
    "DJ Khaled": [("Hip Hop", 7), ("Trap", 6), ("Pop", 6)],
    "Mustard": [("Hip Hop", 8), ("West Coast", 8), ("Trap", 7)],
    "BigXthaPlug": [("Trap", 8), ("Hip Hop", 7)],
    "BossMan Dlow": [("Trap", 8), ("Hip Hop", 6)],
    "Lazer Dim 700": [("Trap", 7), ("Experimental", 6)],
    "Che": [("Trap", 7), ("Experimental", 7)],
    "Dave": [("Hip Hop", 9), ("Drill", 6)],
    "Stormzy": [("Hip Hop", 8), ("Drill", 7)],
    "Skepta": [("Hip Hop", 8), ("Drill", 8), ("Experimental", 6)],
    "AJ Tracey": [("Hip Hop", 7), ("Drill", 7)],
    "Aitch": [("Hip Hop", 7)],
    "Mobb Deep": [("Boom Bap", 9), ("East Coast", 9)],
    "Gang Starr": [("Boom Bap", 10), ("East Coast", 8)],
    "The Notorious B.I.G.": [("Hip Hop", 10), ("East Coast", 10), ("Boom Bap", 8)],
    "Jay-Z": [("Hip Hop", 10), ("East Coast", 9)],
    "Outkast": [("Hip Hop", 10), ("Soul", 7), ("Experimental", 7)],
    "A Tribe Called Quest": [("Hip Hop", 9), ("Boom Bap", 9), ("Soul", 6)],
    "The Roots": [("Hip Hop", 9), ("Soul", 7), ("Boom Bap", 8)],
    "DMX": [("Hip Hop", 9), ("East Coast", 8)],
    "Mos Def": [("Hip Hop", 8), ("Soul", 6), ("Experimental", 6)],
    "Lauryn Hill": [("Hip Hop", 9), ("Soul", 9), ("R&B", 8)],
    "Jadakiss": [("Hip Hop", 8), ("East Coast", 8), ("Boom Bap", 7)],
    "Usher": [("R&B", 10), ("Pop", 7)],
    "Chris Brown": [("R&B", 9), ("Hip Hop", 7), ("Pop", 7)],
    "Beyoncé": [("R&B", 10), ("Pop", 9), ("Soul", 7)],
    "Rihanna": [("R&B", 9), ("Pop", 10), ("Dancehall", 6)],
    "Alicia Keys": [("R&B", 9), ("Soul", 8)],
    "Miguel": [("R&B", 9), ("Soul", 6)],
    "Anderson .Paak": [("R&B", 8), ("Soul", 8), ("Hip Hop", 7)],
    "Victoria Monét": [("R&B", 9), ("Pop", 6)],
    "Jhené Aiko": [("R&B", 9)],
    "Ella Mai": [("R&B", 8)],
    "Giveon": [("R&B", 9)],
    "6lack": [("R&B", 8), ("Hip Hop", 6)],
    "Khalid": [("R&B", 8), ("Pop", 7)],
    "Tinashe": [("R&B", 8), ("Pop", 6), ("Experimental", 5)],
    "Normani": [("R&B", 7), ("Pop", 7)],
    "Maxwell": [("R&B", 9), ("Soul", 9)],
    "John Legend": [("R&B", 8), ("Soul", 8), ("Pop", 6)],
    "Amy Winehouse": [("Soul", 10), ("R&B", 8)],
    "Aretha Franklin": [("Soul", 10), ("R&B", 8)],
    "Marvin Gaye": [("Soul", 10), ("R&B", 7)],
    "Stevie Wonder": [("Soul", 10), ("R&B", 7), ("Pop", 6)],
    "Al Green": [("Soul", 9), ("R&B", 7)],
    "Otis Redding": [("Soul", 9)],
    "Taylor Swift": [("Pop", 10)],
    "Ariana Grande": [("Pop", 10), ("R&B", 7)],
    "Justin Bieber": [("Pop", 9), ("R&B", 7)],
    "Ed Sheeran": [("Pop", 9)],
    "Harry Styles": [("Pop", 8)],
    "Miley Cyrus": [("Pop", 8)],
    "Lady Gaga": [("Pop", 9), ("Experimental", 6)],
    "Bruno Mars": [("Pop", 10), ("Soul", 8), ("R&B", 8)],
    "Adele": [("Pop", 9), ("Soul", 8)],
    "Justin Timberlake": [("Pop", 8), ("R&B", 7)],
    "Calvin Harris": [("House", 9), ("Pop", 8)],
    "David Guetta": [("House", 9), ("Pop", 7)],
    "Skrillex": [("Experimental", 9), ("House", 7)],
    "Diplo": [("House", 8), ("Dancehall", 6), ("Pop", 6)],
    "Tiësto": [("House", 8)],
    "Marshmello": [("House", 7), ("Pop", 7)],
    "Peggy Gou": [("House", 8), ("Tech House", 7)],
    "Bicep": [("Deep House", 8), ("House", 7)],
    "Bonobo": [("Deep House", 8), ("Experimental", 6)],
    "Jamie xx": [("House", 8), ("Experimental", 7)],
    "Chris Lake": [("House", 8), ("Tech House", 8)],
    "CKay": [("Afrobeat", 8), ("Pop", 6)],
    "Joeboy": [("Afrobeat", 8), ("R&B", 6)],
    "BNXN": [("Afrobeat", 7)],
    "Black Sherif": [("Afrobeat", 7), ("Hip Hop", 6)],
    "MoonDeity": [("Phonk", 8)],
    "Hensonn": [("Phonk", 8)],
    "DJ Smokey": [("Phonk", 7), ("Experimental", 5)],
    "Tomppabeats": [("Lo-Fi", 9)],
    "Jinsang": [("Lo-Fi", 8)],
    "eevee": [("Lo-Fi", 8)],
    "Aso": [("Lo-Fi", 8)],
    "Death Grips": [("Experimental", 10), ("Hip Hop", 7)],
    "SOPHIE": [("Experimental", 10), ("Pop", 6)],
    "100 gecs": [("Experimental", 9), ("Pop", 5)],
    "Bladee": [("Experimental", 8), ("Trap", 6), ("Pop", 5)],
    "Ecco2k": [("Experimental", 8), ("Pop", 5)],
    "Yung Lean": [("Experimental", 8), ("Trap", 7), ("Hip Hop", 6)],
    "Sean Paul": [("Dancehall", 10), ("Pop", 7)],
    "Shaggy": [("Dancehall", 9), ("Pop", 7)],
    "Popcaan": [("Dancehall", 9), ("Trap", 5)],
    "Beenie Man": [("Dancehall", 9)],
    "Ice Cube": [("Hip Hop", 9), ("West Coast", 9)],
    "E-40": [("Hip Hop", 8), ("West Coast", 9)],
    "The Game": [("Hip Hop", 8), ("West Coast", 9)],
    "Roddy Ricch": [("Hip Hop", 8), ("Trap", 8), ("West Coast", 7)],
    "Blxst": [("R&B", 8), ("West Coast", 7), ("Hip Hop", 6)],
    "Daddy Yankee": [("Reggaeton", 10), ("Latin Trap", 6), ("Hip Hop", 6)],
    "Don Omar": [("Reggaeton", 9)],
    "Wisin & Yandel": [("Reggaeton", 9)],
    "Arcangel": [("Reggaeton", 9), ("Latin Trap", 8)],
    "De La Ghetto": [("Reggaeton", 8), ("Latin Trap", 8), ("R&B", 6)],
    "Ñengo Flow": [("Reggaeton", 8), ("Trap", 7), ("Hip Hop", 6)],
    "Zion & Lennox": [("Reggaeton", 8)],
    "Ivy Queen": [("Reggaeton", 9), ("Hip Hop", 6)],
    "Natti Natasha": [("Reggaeton", 8), ("Pop", 6), ("Latin Trap", 6)],
    "Becky G": [("Reggaeton", 7), ("Pop", 8), ("Latin Trap", 6)],
    "Darell": [("Reggaeton", 7), ("Latin Trap", 7)],
    "Porta": [("Hip Hop", 8), ("Boom Bap", 7)],
    "La Mala Rodríguez": [("Hip Hop", 9), ("Trap", 6)],
    "ZPU": [("Hip Hop", 7), ("Boom Bap", 7)],
    "La Excepción": [("Hip Hop", 7), ("Experimental", 5)],
    "Gata Cattana": [("Hip Hop", 8), ("Experimental", 6)],
}

# Artist origin metadata: name -> (region, language).
# Regions: US, UK, Canada, LATAM, Caribbean, Spain, Africa, Europe, Other.
# Only non-default entries listed; default is (None, "en").
# The "LATAM" pool matches region IN (LATAM, Caribbean);
# the "En español" pool matches language == es.


# Artist origin metadata: name -> (region, language).
# Regions: US, UK, Canada, LATAM, Caribbean, Spain, Africa, Europe, Other.
# Only non-default entries listed; default is (None, "en").
# The "LATAM" pool matches region IN (LATAM, Caribbean);
# the "En español" pool matches language == es.
ARTIST_META: dict[str, tuple[str | None, str]] = {
    "Bad Bunny": ("Caribbean", "es"), "Anuel AA": ("Caribbean", "es"),
    "Ozuna": ("Caribbean", "es"), "Myke Towers": ("Caribbean", "es"),
    "Rauw Alejandro": ("Caribbean", "es"), "Young Miko": ("Caribbean", "es"),
    "Mora": ("Caribbean", "es"), "Jhayco": ("Caribbean", "es"),
    "El Alfa": ("Caribbean", "es"), "Eladio Carrión": ("Caribbean", "es"),
    "Yovngchimi": ("Caribbean", "es"), "Hades66": ("Caribbean", "es"),
    "Vybz Kartel": ("Caribbean", "en"), "Skillibeng": ("Caribbean", "en"),
    "Masicka": ("Caribbean", "en"), "Chronic Law": ("Caribbean", "en"),
    "Shenseea": ("Caribbean", "en"), "Alkaline": ("Caribbean", "en"),
    "Spice": ("Caribbean", "en"),
    "Feid": ("LATAM", "es"), "Duki": ("LATAM", "es"), "YSY A": ("LATAM", "es"),
    "Bizarrap": ("LATAM", "es"), "Nicki Nicole": ("LATAM", "es"),
    "Cazzu": ("LATAM", "es"), "Khea": ("LATAM", "es"),
    "Nathy Peluso": ("LATAM", "es"), "Cris Mj": ("LATAM", "es"),
    "FloyyMenor": ("LATAM", "es"), "Blessd": ("LATAM", "es"),
    "Ryan Castro": ("LATAM", "es"), "Karol G": ("LATAM", "es"),
    "Shakira": ("LATAM", "es"), "J Balvin": ("LATAM", "es"),
    "Santa Fe Klan": ("LATAM", "es"), "Alemán": ("LATAM", "es"),
    "Gera MX": ("LATAM", "es"), "Arca": ("LATAM", "es"),
    "Snow Tha Product": ("US", "es"),
    "Nach": ("Spain", "es"), "SFDK": ("Spain", "es"),
    "Violadores del Verso": ("Spain", "es"), "ToteKing": ("Spain", "es"),
    "Shotta": ("Spain", "es"), "Rapsusklei": ("Spain", "es"),
    "El Chojin": ("Spain", "es"), "Ayax y Prok": ("Spain", "es"),
    "Natos y Waor": ("Spain", "es"), "Foyone": ("Spain", "es"),
    "C. Tangana": ("Spain", "es"), "Aitana": ("Spain", "es"),
    "Lola Índigo": ("Spain", "es"), "El Bobe": ("Spain", "es"),
    "Canserbero": ("LATAM", "es"), "Apache": ("LATAM", "es"),
    "Lil Supa": ("LATAM", "es"), "Akapellah": ("LATAM", "es"),
    "Acru": ("LATAM", "es"), "Trueno": ("LATAM", "es"),
    "Wos": ("LATAM", "es"), "Ca7riel y Paco Amoroso": ("LATAM", "es"),
    "Dillom": ("LATAM", "es"), "Ana Tijoux": ("LATAM", "es"),
    "Portavoz": ("LATAM", "es"), "Cartel de Santa": ("LATAM", "es"),
    "C-Kan": ("LATAM", "es"), "Neutro Shorty": ("LATAM", "es"),
    "Big Soto": ("LATAM", "es"), "Pablo Chill-E": ("LATAM", "es"),
    "Sech": ("LATAM", "es"), "Piso 21": ("LATAM", "es"),
    "Kafu Banton": ("LATAM", "es"), "Girl Ultra": ("LATAM", "es"),
    "Nsqk": ("LATAM", "es"), "Micro TDH": ("LATAM", "es"),
    "Manuel Turizo": ("LATAM", "es"), "Sebastián Yatra": ("LATAM", "es"),
    "Camilo": ("LATAM", "es"), "Emilia": ("LATAM", "es"),
    "Tini": ("LATAM", "es"), "María Becerra": ("LATAM", "es"),
    "Chancha Vía Circuito": ("LATAM", "es"), "Nicola Cruz": ("LATAM", "es"),
    "Lápiz Conciente": ("Caribbean", "es"), "Vico C": ("Caribbean", "es"),
    "Tego Calderón": ("Caribbean", "es"), "Orishas": ("Caribbean", "es"),
    "Los Aldeanos": ("Caribbean", "es"),
    "Villano Antillano": ("Caribbean", "es"), "Brray": ("Caribbean", "es"),
    "Lomiiel": ("Caribbean", "es"), "Little Homie": ("Caribbean", "es"),
    "Dalex": ("Caribbean", "es"), "Lenny Tavárez": ("Caribbean", "es"),
    "Lyanno": ("Caribbean", "es"), "Cimafunk": ("Caribbean", "es"),
    "Cuco": ("US", "es"), "Omar Apollo": ("US", "es"),
    "Kali Uchis": ("US", "es"), "Becky G": ("US", "es"),
    "Jinsang": ("US", "en"), "DJ Smokey": ("US", "en"),
    "Dave": ("UK", "en"), "Stormzy": ("UK", "en"), "Skepta": ("UK", "en"),
    "AJ Tracey": ("UK", "en"), "Aitch": ("UK", "en"),
    "Ella Mai": ("UK", "en"), "Amy Winehouse": ("UK", "en"),
    "Adele": ("UK", "en"), "Ed Sheeran": ("UK", "en"),
    "Harry Styles": ("UK", "en"), "Calvin Harris": ("UK", "en"),
    "Bicep": ("UK", "en"), "Bonobo": ("UK", "en"), "Jamie xx": ("UK", "en"),
    "Chris Lake": ("UK", "en"), "SOPHIE": ("UK", "en"),
    "Justin Bieber": ("Canada", "en"),
    "David Guetta": ("Europe", "en"), "Tiësto": ("Europe", "en"),
    "Bladee": ("Europe", "en"), "Ecco2k": ("Europe", "en"),
    "Yung Lean": ("Europe", "en"), "MoonDeity": ("Europe", "en"),
    "Hensonn": ("Europe", "en"),
    "Peggy Gou": ("Other", "en"), "Tomppabeats": ("Other", "en"),
    "eevee": ("Other", "en"), "Aso": ("Other", "en"),
    "CKay": ("Africa", "en"), "Joeboy": ("Africa", "en"),
    "BNXN": ("Africa", "en"), "Black Sherif": ("Africa", "en"),
    "Sean Paul": ("Caribbean", "en"), "Shaggy": ("Caribbean", "en"),
    "Popcaan": ("Caribbean", "en"), "Beenie Man": ("Caribbean", "en"),
    "Rihanna": ("Caribbean", "en"),
    "Daddy Yankee": ("Caribbean", "es"), "Don Omar": ("Caribbean", "es"),
    "Wisin & Yandel": ("Caribbean", "es"), "Arcangel": ("Caribbean", "es"),
    "De La Ghetto": ("Caribbean", "es"), "Ñengo Flow": ("Caribbean", "es"),
    "Zion & Lennox": ("Caribbean", "es"), "Ivy Queen": ("Caribbean", "es"),
    "Natti Natasha": ("Caribbean", "es"), "Darell": ("Caribbean", "es"),
    "Porta": ("Spain", "es"), "La Mala Rodríguez": ("Spain", "es"),
    "ZPU": ("Spain", "es"), "La Excepción": ("Spain", "es"),
    "Gata Cattana": ("Spain", "es"),
    "Rosalía": ("Spain", "es"), "Quevedo": ("Spain", "es"),
    "Rels B": ("Spain", "es"), "Cruz Cafuné": ("Spain", "es"),
    "Delaossa": ("Spain", "es"), "Morad": ("Spain", "es"),
    "Beny Jr": ("Spain", "es"), "JC Reyes": ("Spain", "es"),
    "Central Cee": ("UK", "en"), "Headie One": ("UK", "en"),
    "Nemzzz": ("UK", "en"), "Russ Millions": ("UK", "en"),
    "K-Trap": ("UK", "en"), "Fred Again": ("UK", "en"),
    "Disclosure": ("UK", "en"), "Dua Lipa": ("UK", "en"),
    "Charli XCX": ("UK", "en"), "EsDeeKid": ("UK", "en"),
    "fakemink": ("UK", "en"),
    "Drake": ("Canada", "en"), "The Weeknd": ("Canada", "en"),
    "Daniel Caesar": ("Canada", "en"), "PARTYNEXTDOOR": ("Canada", "en"),
    "Burna Boy": ("Africa", "en"), "Wizkid": ("Africa", "en"),
    "Tems": ("Africa", "en"), "Davido": ("Africa", "en"),
    "Fireboy DML": ("Africa", "en"), "Omah Lay": ("Africa", "en"),
    "Seyi Vibez": ("Africa", "en"), "Shallipopi": ("Africa", "en"),
    "Uncle Waffles": ("Africa", "en"), "Rema": ("Africa", "en"),
    "Ayra Starr": ("Africa", "en"), "Tyla": ("Africa", "en"),
    "Nujabes": ("Other", "en"), "Fisher": ("Other", "en"),
    "Dom Dolla": ("Other", "en"),
}
